name: Auto Build Termux App

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone -b v0.118.0 https://github.com/termux/termux-app
    - name: Modify
      run: |
        ###
        cd termux-app
        rep(){ sed -i "s/$1/$2/g" $3 ;}
        
        # build arm64-v8a only
        rep "abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'" "abiFilters 'arm64-v8a'" app/build.gradle
        
        # chage extra key layout
        rep "\\[\\['ESC','\\/',{key: '-', popup: '|'},'HOME','UP','END','PGUP'\\], \\['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN'\\]\\]" \
        "\\[\\[{key: '~',popup: '\\\`'}, {key: '\\\\\\\\\\/', popup: '?'}, {key: ':', popup: ';'}, {key: '!', popup: {macro: 'ESC :!', display: '!cmd'}}, {key: '-', popup: '_'}, {key: '=', popup: '+'}, {key: 'UP', popup: 'PGUP'}, {key: 'KEYBOARD', popup: {macro: 'exit ENTER', display: 'exit'}}],[{key: 'ESC', popup: {macro: 'ESC :q ENTER', display: 'quit'}}, {key: 'TAB', popup: {macro: 'ESC :w ENTER', display: 'save'}}, {key: 'CTRL', popup: {macro: 'ESC F5 ENTER', display: 'RUN'}}, {key: 'ALT', popup: '*'}, {key: 'BACKSLASH', popup: '|'}, {key: 'LEFT', popup: 'HOME'}, {key: 'DOWN', popup: 'PGDN'}, {key: 'RIGHT', popup: 'END'}\\]\\]" \
        termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java
        
        # use lessKnownCharacterDisplay and arrowTriangleVariationDisplay
        sed -i '163 i putAll(LESS_KNOWN_CHARACTERS_DISPLAY);' termux-shared/src/main/java/com/termux/shared/terminal/io/extrakeys/ExtraKeysConstants.java
        sed -i '163 i putAll(ARROW_TRIANGLE_VARIATION_DISPLAY);' termux-shared/src/main/java/com/termux/shared/terminal/io/extrakeys/ExtraKeysConstants.java
        
        # remove settingsButtonView
        sed -i "523asettingsButton.setVisibility(View.GONE);" app/src/main/java/com/termux/app/TermuxActivity.java

        # change core version
        # sed -i 162,166d app/build.gradle
        # addLine(){
        #     sed -i "162a$1" app/build.gradle
        # }
        # addLine 'downloadBootstrap("aarch64", "dee3c8c19c9b3d2f162c4ea759c91774ee537fc977c38ca8d111cc74208b0531", version)'
        # addLine 'downloadBootstrap("arm",     "64129d36019fc24705a682aae9aefae0ca3df5ed2454768f40b9cd4774e125af", version)'
        # addLine 'downloadBootstrap("i686",    "fb163955d1980d02484cd764c646860b2399c6d9648bacc962bf2b033f1c78ce", version)'
        # addLine 'downloadBootstrap("x86_64",  "4c2517f311aea2336ffc6bc2ee667b63e66704de92f6cab55501d4b1f6492d2f", version)'
        # addLine 'def version = "2022.02.13-r1"'

    - name: Build
      run: |
        cd termux-app
        ./gradlew assembleDebug

    - name: Copy and rename files
      run: |
        remote_version=$(cat termux-app/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "lastest version: $remote_version"
        cd termux-app/app/build/outputs/apk/debug
        for var in $(ls)
        do
          if [ ${var##*.} == "apk" ];then
             mv -f "$var" $(echo "$var"|sed 's/app/termux-app/' |sed 's/-debug/'_${remote_version}/)
          fi
        done
        
        for var in universal arm64-v8a armeabi-v7a x86_64 x86
          do mkdir -p $var && mv *$var*.apk $var
        done

#     - name: Store generated APK file
#       uses: actions/upload-artifact@v2
#       with:
#         name: termux-app
#         path: ./termux-app/app/build/outputs/apk/debug
# #         path: ./termux-app/termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java     # debug

    - name: Store generated universal APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-universal
        path: |
            ./termux-app/app/build/outputs/apk/debug/universal
            ./termux-app/app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated arm64-v8a APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-arm64-v8a
        path: |
          ./termux-app/app/build/outputs/apk/debug/arm64-v8a
          ./termux-app/app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated armeabi-v7a APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-armeabi-v7a
        path: |
          ./termux-app/app/build/outputs/apk/debug/armeabi-v7a
          ./termux-app/app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated x86_64 APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-x86_64
        path: |
          ./termux-app/app/build/outputs/apk/debug/x86_64
          ./termux-app/app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated x86 APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-x86
        path: |
          ./termux-app/app/build/outputs/apk/debug/x86
          ./termux-app/app/build/outputs/apk/debug/output-metadata.json
#     - name: Upload Apk to WeTransfer
#       run: |
#         cd termux-app
#          curl -sL https://git.io/file-transfer | sh
#         ./transfer wet ./app/build/outputs/apk/debug/*.apk
